/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BusinessType = IDL.Variant({
  'gym' : IDL.Null,
  'retail' : IDL.Null,
  'cafe' : IDL.Null,
  'salon' : IDL.Null,
  'restaurant' : IDL.Null,
});

export const idlService = IDL.Service({
  'generateAd' : IDL.Func(
      [BusinessType, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BusinessType = IDL.Variant({
    'gym' : IDL.Null,
    'retail' : IDL.Null,
    'cafe' : IDL.Null,
    'salon' : IDL.Null,
    'restaurant' : IDL.Null,
  });
  
  return IDL.Service({
    'generateAd' : IDL.Func(
        [BusinessType, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };